server:
  port: 8888
  servlet:
    context-path: /swagger

# json序列化配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.137.12:3306/pipixia?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Level_2

  # 切换环境配置
  profiles:
    active: dev
#  aop:
#    auto: true #启动aop配置

# 指定某个包下的日志级别
logging:
  pattern:
    #日志格式
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) - %clr([%t]){faint} %X{log_id} %clr(%logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p - [%t] %X{log_id} %logger{39} : %m%n%wEx"
    level:
      root: info

test:
  value: 8888999